name: Compile ESP32 TTS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Install ESP32 Board Package
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install Dependencies Manually
        run: |
          # Buat folder library jika belum ada
          mkdir -p libraries
          # Clone library langsung dari sumbernya
          git clone https://github.com/schreibfaul1/ESP32-audioI2S.git libraries/ESP32-audioI2S

            - name: Compile
        run: |
          # Kita tambahkan --build-property untuk memaksa partisi lebih besar lagi
          # Dan kita coba buang library yang tidak terpakai dengan --build-property
          arduino-cli compile --fqbn esp32:esp32:esp32s3 \
          --build-property "build.partitions=huge_app" \
          --build-property "build.flash_size=4MB" \
          --build-path ./build_output \
          ./src --libraries ./libraries


      - name: Debug - List files
        run: ls -R build_output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-tts-bin
          path: build_output/*.bin

