name: Compile ESP32 TTS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Install ESP32 Board Package
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install Dependencies Manually
        run: |
          # Buat folder library jika belum ada
          mkdir -p libraries
          # Clone library langsung dari sumbernya
          git clone https://github.com/schreibfaul1/ESP32-audioI2S.git libraries/ESP32-audioI2S

      - name: Compile
        run: |
          # Menambahkan --build-property partition_scheme=huge_app
          arduino-cli compile --fqbn esp32:esp32:esp32s3 \
          --build-property "build.partitions=huge_app" \
          --build-property "upload.maximum_size=3145728" \
          ./src --libraries ./libraries
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-tts-bin
          # Kita pakai wildcard ** agar dia cari file .bin di folder manapun
          path: |
            **/*.bin
            !**/.git/**
